packages:
  - example

allowBuilds:
  core-js: false

minimumReleaseAgeExclude:
  - '@rsbuild/*'
  - '@rslib/*'
  - '@rslint/*'
  - '@rspack/*'
  - '@rspress/*'
  - '@rstackjs/*'
  - '@rstest/*'
  - '@typescript/*'
  - 'rsbuild-plugin-*'
  - rstack
  - typescript
